name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # ---------------------------------------
          #   APARÃŠNCIA (somente topo)
          # ---------------------------------------
          template: classic
          base: header, metadata

          # ---------------------------------------
          #   LINGUAGENS
          # ---------------------------------------
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10

          # ---------------------------------------
          #   ACHIEVEMENTS
          # ---------------------------------------
          plugin_achievements: yes
          plugin_achievements_threshold: S
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
