name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # ----------------------------------------------------
          #   APARÊNCIA
          # ----------------------------------------------------
          template: classic
          base: header, activity, community, repositories, metadata

          # ----------------------------------------------------
          #  MÓDULOS DE ESTATÍSTICA
          # ----------------------------------------------------
          plugin_lines: yes
          plugin_traffic: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # ----------------------------------------------------
          #   CONTRIBUIÇÕES (heatmap)
          # ----------------------------------------------------
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          # ----------------------------------------------------
          #   LINGUAGENS
          # ----------------------------------------------------
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10

          # ----------------------------------------------------
          #   ACHIEVEMENTS
          # ----------------------------------------------------
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed

          # ----------------------------------------------------
          #   HABILIDADES SOCIAIS
          # ----------------------------------------------------
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # ----------------------------------------------------
          #   GRÁFICO DE COMMIT SEMANAL
          # ----------------------------------------------------
          plugin_calendar: yes
          plugin_calendar_limit: 5
